python train.py --dataset cifar10 \
      --name cifar10-wrn28x10 \
      --dataroot /home/user/data/ \
      --checkpoint /home/user/runs/latent/ \
      --num_k 6 \
      --epochs 200 \
      --batch-size 128 \
      --lr 0.1 \
      --weight-decay 5.0e-4 \
      --model wrn \
      --layers 28 \
      --widen-factor 10 \
      --cutmix_prob 0.5 \
      --cutmix True
