python train.py --dataset cifar10 \
      --name cifar10-shake26_2x32d \
      --dataroot /home/user/data/ \
      --checkpoint /home/user/runs/latent/ \
      --num_k 6 \
      --epochs 1800 \
      --batch-size 128 \
      --lr 0.01 \
      --weight-decay 0.001 \
      --model shakeshake \
      --layers 26 \
      --widen-factor 32 \
      --cutmix_prob 0.5 \
      --cutmix True
